name: skills-cli-backend
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: jerry
          POSTGRES_PASSWORD: seinfeld
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://jerry:seinfeld@localhost:5432/skills-cli-backend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.5
      - run: npm ci
      - run: npm run build
      # run the migration in the test database
      - run: npm run db:push
      - run: npm run test
